### ISSUE TITLE
Suggestion for Dashboard

### ISSUE THREAD

**Issue by JasonJiangs** [caranha/Koudou#18]

**Comment by JasonJiangs** [comment]
An initial version of the Dashboard has been published in a new branch dashboard-management. It is easy to run with README files. 

There are already some clues (TODO list) of how to complete the dashboard app that have been written in the README file. 
More suggestions about how to utilize logs and csv result files to make this interactive visualized dashboard to be put forward here.

**Comment by caranha** [comment]
Hey Jason, thank you for that!

Following the discussion with Tony yesterday, we can think of some things that are expected from the Dashboard:
- Basic information about the simulation being displayed: 
  - How much time it covers (in simulation time)
  - How many agents are in the simulation
  - What is the area being simulated
  - Number of students, workers, etc.
  - Other basic information
